name: Build PDF Manual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install linux libraries
      run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev \
                                  libcurl4-openssl-dev \
                                  libgdal-dev \
                                  libproj-dev \
                                  libudunits2-dev \
                                  libharfbuzz-dev \
                                  libfribidi-dev \
                                  pandoc


    - name: Install R dependencies
      run: |
        R -e "install.packages('devtools')"
        R -e "install.packages('roxygen2')"
        R -e "install.packages('pkgdown')"

    - name: Install R packages
      run: |
        source("preprocessing/install_imports.R")
      shell: Rscript {0}

    - name: cleanup_reference_manual
      run: |
        source("preprocessing/cleanup_reference_manual.R")
      shell: Rscript {0}

    - name: Build and document package
      run: |
        R -e "devtools::document()"
        R -e "pkgdown::build_site()"

    - name: Commit and push changes
      if: success()
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.AUTOMATISATION }}
        commit_prefix: "[AUTO]"
        commit_message: "update fistools"
        debug: ${{ secrets.ACTIONS_STEP_DEBUG }}
        target_branch: ${{ github.head_ref || github.ref_name }}
