name: Build PDF Manual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install linux libraries
      run: |
          sudo apt install libsodium-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev libproj-dev
          sudo apt install libudunits2-dev
          sudo apt install libharfbuzz-dev
          sudo apt install libfribidi-dev

    - name: Install R dependencies
      run: |
        R -e "install.packages('devtools')"
        R -e "install.packages('roxygen2')"

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Install R packages
      run: |
        source("preprocessing/install_imports.R")
      shell: Rscript {0}

    - name: Build and document package
      run: |
        R -e "devtools::document()"

    - name: Generate PDF manual
      run: |
        R CMD Rd2pdf . -o fistools.pdf

    - name: Upload PDF manual
      uses: actions/upload-artifact@v3
      with:
        name: fistools-manual
        path: fistools.pdf
