name: Trigger Build pkgdown Site

on:
  workflow_run:
    workflows: ["Increment version"]  # Ensure this matches the name in increment_version.yaml
    types:
      - completed
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Configure GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Trigger Build pkgdown site
      run: gh workflow run "Build pkgdown site"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
